name: provider_shopper
description: A shopping app sample that uses Provider for state management.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  products_api:
    path: ../server
  products_repository:
    path: packages/products_repository

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
